// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5_xwWBmoIuSBN5snQoW5ZIvbcHfz_t0Q',
    appId: '1:256482633044:web:36b12b5210ccc06271d4c1',
    messagingSenderId: '256482633044',
    projectId: 'ustaadji-pk',
    authDomain: 'ustaadji-pk.firebaseapp.com',
    storageBucket: 'ustaadji-pk.firebasestorage.app',
    measurementId: 'G-89KVVLCH4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKMtfSDPM4mIqf8efEh-aGUAwjMyjbgIM',
    appId: '1:256482633044:android:93942b7ed8a1b98a71d4c1',
    messagingSenderId: '256482633044',
    projectId: 'ustaadji-pk',
    storageBucket: 'ustaadji-pk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxc_aUxFJ3Xq4KDIU3ZTt0jEuS773g3f4',
    appId: '1:256482633044:ios:9077452c29e2899e71d4c1',
    messagingSenderId: '256482633044',
    projectId: 'ustaadji-pk',
    storageBucket: 'ustaadji-pk.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxc_aUxFJ3Xq4KDIU3ZTt0jEuS773g3f4',
    appId: '1:256482633044:ios:9077452c29e2899e71d4c1',
    messagingSenderId: '256482633044',
    projectId: 'ustaadji-pk',
    storageBucket: 'ustaadji-pk.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5_xwWBmoIuSBN5snQoW5ZIvbcHfz_t0Q',
    appId: '1:256482633044:web:36b12b5210ccc06271d4c1',
    messagingSenderId: '256482633044',
    projectId: 'ustaadji-pk',
    authDomain: 'ustaadji-pk.firebaseapp.com',
    storageBucket: 'ustaadji-pk.firebasestorage.app',
    measurementId: 'G-89KVVLCH4B',
  );
}
